port: 8080
postgres:
  login: admin
  host: db
  port: 5432
  name: postgres
  password: root

kafka:
  bootstrapServers: bachelor-kafka:9092
  consumer:
    groupId: actor_consumer
    topics: [actor_topic]
  producer:
    topics: target_topic
  metrics:
    prefix: actor
    latency: true
    lag: true
    inputMessagesPerSec:
      duration: 5s
    outputMessagesPerSec:
      duration: 5s