port: 8080
postgres:
  login: admin
  host: localhost
  port: 5436
  name: postgres
  password: root

kafka:
  bootstrapServers: localhost:29092
  consumer:
    groupId: actor_consumer
    topics: [actor_topic]
  producer:
    topics: target_topic
  metrics:
    prefix: actor
    latency: true
    lag: true
    inputMessagesPerSec:
      count: true
      
    outputMessagesPerSec:
      count: true
      