port: 8080
postgres:
  login: admin
  host: db
  port: 5432
  name: postgres
  password: root
kafka:
  bootstrapServers: bachelor-kafka:9092
  consumer:
    groupId: filter_consumer
    topics: [filter_topic]
  producer:
    topics: transformer_topic
  metrics:
    prefix: filter
    latency: true
    lag: true
    filtrationParams: true
    inputMessagesPerSec:
      count: true
      
    outputMessagesPerSec:
      count: true
      