port: 8080
postgres:
  login: admin
  host: localhost
  port: 5436
  name: postgres
  password: root
kafka:
  bootstrapServers: localhost:29092
  consumer:
    groupId: filter_consumer
    topics: [filter_topic]
  producer:
    topics: transformer_topic
  metrics:
    prefix: filter
    latency: true
    lag: true
    inputMessagesPerSec:
      count: true
      
    outputMessagesPerSec:
      count: true
      