port: 8080
postgres:
  login: admin
  host: localhost
  port: 5436
  name: postgres
  password: root

kafka:
  bootstrapServers: localhost:29092
  consumer:
    groupId: source_consumer
    topics: [source_topic]
  producer:
    topics: filter_topic
  metrics:
    prefix: source
    latency: true
    lag: true
    inputMessagesPerSec:
      count: true
      
    outputMessagesPerSec:
      count: true
      