port: 8080
postgres:
  login: admin
  host: db
  port: 5432
  name: postgres
  password: root

kafka:
  bootstrapServers: bachelor-kafka:9092
  consumer:
    groupId: enricher_consumer
    topics: [enricher_topic]
  producer:
    topics: actor_topic
  metrics:
    prefix: enricher
    latency: true
    lag: true
    inputMessagesPerSec:
      duration: 5s
    outputMessagesPerSec:
      duration: 5s