port: 8080
postgres:
  login: admin
  host: localhost
  port: 5436
  name: postgres
  password: root

kafka:
  bootstrapServers: localhost:29092
  consumer:
    groupId: enricher_consumer
    topics: [enricher_topic]
  producer:
    topics: actor_topic
  metrics:
    prefix: enricher
    latency: true
    lag: true
    inputMessagesPerSec:
      count: true
      
    outputMessagesPerSec:
      count: true
      