port: 8080
postgres:
  login: admin
  host: localhost
  port: 5436
  name: postgres
  password: root

kafka:
  bootstrapServers: localhost:29092
  consumer:
    groupId: deduplicator_consumer
    topics: [deduplicator_topic]
  producer:
    topics: enricher_topic
  metrics:
    prefix: deduplicator
    latency: true
    lag: true
    inputMessagesPerSec:
      count: true
      
    outputMessagesPerSec:
      count: true
      