port: 8080
postgres:
  login: admin
  host: localhost
  port: 5436
  name: postgres
  password: root

kafka:
  bootstrapServers: localhost:29092
  consumer:
    groupId: transformer_consumer
    topics: [transformer_topic]
  producer:
    topics: deduplicator_topic
  metrics:
    prefix: transformer
    latency: true
    lag: true
    inputMessagesPerSec:
      count: true
      
    outputMessagesPerSec:
      count: true
      