port: 8080
postgres:
  login: admin
  host: db
  port: 5432
  name: postgres
  password: root

kafka:
  bootstrapServers: bachelor-kafka:9092
  consumer:
    groupId: transformer_consumer
    topics: [transformer_topic]
  producer:
    topics: deduplicator_topic
  metrics:
    prefix: transformer
    latency: true
    lag: true
    filtrationParams: true
    inputMessagesPerSec:
      count: true
      
    outputMessagesPerSec:
      count: true
      